//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI5TypeScriptGeneratorJsonGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("object : any\r\nfunction : any\r\nint : number\r\nMap : any\r\nundefined : \r\ntrue : boole" +
            "an\r\nnull : ")]
        public string TypeReplacements {
            get {
                return ((string)(this["TypeReplacements"]));
            }
            set {
                this["TypeReplacements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"sap/m/designtime/api.json
sap/tnt/designtime/api.json
sap/ui/commons/designtime/api.json
sap/ui/core/designtime/api.json
sap/ui/demokit/designtime/api.json
sap/ui/dt/designtime/api.json
sap/ui/layout/designtime/api.json
sap/ui/suite/designtime/api.json
sap/ui/table/designtime/api.json
sap/ui/unified/designtime/api.json
sap/ui/ux3/designtime/api.json
sap/uxap/designtime/api.json")]
        public string RestEndpoints {
            get {
                return ((string)(this["RestEndpoints"]));
            }
            set {
                this["RestEndpoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputFolder {
            get {
                return ((string)(this["OutputFolder"]));
            }
            set {
                this["OutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://openui5.hana.ondemand.com/test-resources")]
        public string ServiceAddress {
            get {
                return ((string)(this["ServiceAddress"]));
            }
            set {
                this["ServiceAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.40")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
    }
}
