//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI5TypeScriptGeneratorJsonGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("* : any\r\nany[] : any[]\r\narray : any[]\r\nArray : any[]\r\narray.<array.<string>> : st" +
            "ring[][]\r\narraybuffer : any\r\nbAlwaysShow : boolean\r\nblob : any\r\nBoolean : boolea" +
            "n\r\nCalendarAppointment : any\r\nControl : sap.ui.Core.Control\r\ncreateDefaultConten" +
            "t : any\r\ndate : any\r\nDate : any\r\nDomNode : any\r\nDOMNode : any\r\ndomRef : any\r\nDom" +
            "Ref : any\r\nDOMRef : any\r\nDomRef[] : any[]\r\nelement : any\r\nElement : any\r\nElement" +
            "[] : any[]\r\nEntityType : any\r\nError : any\r\nevent : any\r\nfloat : number\r\nfunction" +
            " : any\r\nGenerator : any\r\nHTMLElement : any\r\nint : number\r\nint[] : number[]\r\ninte" +
            "ger : number\r\njQuery : any\r\njQuery.promise : any\r\njQuery.sap.log : any\r\njQuery.s" +
            "ap.util.ResourceBundle : any\r\nManagedObjectMetadata : any\r\nmap : any\r\nMap : any\r" +
            "\nMenuButton : any\r\nnull :\r\nNumber : number\r\nNumber[] : number[]\r\nobjec : any\r\nob" +
            "ject : any\r\nObject : any\r\nobject[] : any[]\r\nObjectNumber : number\r\noWindow : any" +
            "\r\nP13nConditionOperation[] : any[]\r\nPromise : any\r\nqunit : any\r\nregexp : string\r" +
            "\nsap.m.DynamicSideContent : sap.ui.layout.DynamicSideContent\r\nsap.ui.base.Manage" +
            "Object : sap.ui.base.ManagedObject\r\nsap.ui.Core.Control : sap.ui.core.Control\r\ns" +
            "ap.ui.core.Controller : sap.ui.core.mvc.Controller\r\nsap.ui.core.InvisibleControl" +
            " : any\r\nsap.util.Properties : any\r\nScrollEnablement : sap.ui.core.delegate.Scrol" +
            "lEnablement\r\nsting[] : string[]\r\nString : string\r\nstring[] : string[]\r\nString[] " +
            ": string[]\r\nTablePersoController : any\r\nTablePersoDialog : any\r\nTabStripItem : a" +
            "ny\r\nTouch : any\r\nTouchList : any\r\ntrue : boolean\r\nUI5EntityCueCardStyle : any\r\nu" +
            "ndefined : any\r\nWindow : any")]
        public string TypeReplacements {
            get {
                return ((string)(this["TypeReplacements"]));
            }
            set {
                this["TypeReplacements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"sap/m/designtime/api.json
sap/tnt/designtime/api.json
sap/ui/commons/designtime/api.json
sap/ui/core/designtime/api.json
sap/ui/demokit/designtime/api.json
sap/ui/dt/designtime/api.json
sap/ui/layout/designtime/api.json
sap/ui/suite/designtime/api.json
sap/ui/table/designtime/api.json
sap/ui/unified/designtime/api.json
sap/ui/ux3/designtime/api.json
sap/uxap/designtime/api.json")]
        public string RestEndpoints {
            get {
                return ((string)(this["RestEndpoints"]));
            }
            set {
                this["RestEndpoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputFolder {
            get {
                return ((string)(this["OutputFolder"]));
            }
            set {
                this["OutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://openui5.hana.ondemand.com/test-resources")]
        public string ServiceAddress {
            get {
                return ((string)(this["ServiceAddress"]));
            }
            set {
                this["ServiceAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.40")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"sap.ui.core.BusyIndicator : Ui5Enum
sap.ui.core.Collision : string
sap.ui.core.CSSSize : string
sap.ui.core.Dock : string
sap.ui.core.ID : string
sap.ui.core.Popup.Dock : string
sap.ui.core.URI : string
sap.ui.core.ws.ReadyState : Ui5Enum
sap.ui.layout.BlockBackgroundType : Ui5Enum
sap.ui.layout.form.GridElementCells : string|number
sap.ui.layout.GridIndent : string
sap.ui.layout.GridSpan : string
sap.ui.model.analytics.odata4analytics.SortOrder : Ui5Enum
sap.ui.model.BindingMode : Ui5Enum
sap.ui.model.FilterType : Ui5Enum
sap.ui.model.odata.CountMode : Ui5Enum
sap.ui.suite.TaskCircleColor : string")]
        public string TypeDefinitions {
            get {
                return ((string)(this["TypeDefinitions"]));
            }
            set {
                this["TypeDefinitions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extends :\r\ngetMetadata :")]
        public string SkipMethods {
            get {
                return ((string)(this["SkipMethods"]));
            }
            set {
                this["SkipMethods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PostProcessing {
            get {
                return ((string)(this["PostProcessing"]));
            }
            set {
                this["PostProcessing"] = value;
            }
        }
    }
}
