//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI5TypeScriptGeneratorJsonGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("* : any\r\nany[] : any[]\r\narray : any[]\r\nArray : any[]\r\narray.<array.<string>> : st" +
            "ring[][]\r\narraybuffer : any\r\nbAlwaysShow : boolean\r\nblob : any\r\nBoolean : boolea" +
            "n\r\nCalendarAppointment : any\r\nControl : sap.ui.Core.Control\r\ncreateDefaultConten" +
            "t : any\r\ndate : any\r\nDate : any\r\nDomNode : any\r\nDOMNode : any\r\ndomRef : any\r\nDom" +
            "Ref : any\r\nDOMRef : any\r\nDomRef[] : any[]\r\nelement : any\r\nElement : any\r\nElement" +
            "[] : any[]\r\nEntityType : any\r\nError : any\r\nevent : any\r\nfloat : number\r\nfunction" +
            " : any\r\nGenerator : any\r\nHTMLElement : any\r\nint : number\r\nint[] : number[]\r\ninte" +
            "ger : number\r\nInvisibleControl : any\r\njQuery : any\r\njQuery.promise : any\r\njQuery" +
            ".Promise : any\r\njQuery.sap.log : jQuery.sap.log.Logger\r\nmap : any\r\nMap : any\r\nMe" +
            "nuButton : any\r\nnull :\r\nNumber : number\r\nNumber[] : number[]\r\nobjec : any\r\nobjec" +
            "t : any\r\nObject : any\r\nobject[] : any[]\r\nObjectNumber : number\r\noWindow : any\r\nP" +
            "romise : any\r\nregexp : string\r\nsap.m.Control : sap.ui.core.Control\r\nsap.m.Dynami" +
            "cSideContent : sap.ui.layout.DynamicSideContent\r\nsap.m.P13nConditionOperation : " +
            "any\r\nsap.m.P13nConditionOperation[] : any[]\r\nsap.m.TabStripItem : any\r\nsap.ui.ba" +
            "se.ManagedObjectMetadata : any\r\nsap.ui.base.ManageObject : sap.ui.base.ManagedOb" +
            "ject\r\nsap.ui.Core.Control : sap.ui.core.Control\r\nsap.ui.core.Controller : sap.ui" +
            ".core.mvc.Controller\r\nsap.ui.core.Integer : sap.ui.model.type.Integer\r\nsap.ui.co" +
            "re.InvisibleControl : any\r\nsap.ui.core.message.MessageModel : sap.ui.model.messa" +
            "ge.MessageModel\r\nsap.ui.core.Model : sap.ui.model.Model\r\nsap.ui.core.String : sa" +
            "p.ui.model.type.String\r\nsap.ui.demokit.UI5EntityCueCardStyle : any\r\nsap.ui.messa" +
            "ge.MessagePaser : sap.ui.core.message.MessageParser\r\nsap.ui.message.MessageProce" +
            "ssor : sap.ui.core.message.MessageProcessor\r\nsap.ui.model.analytics.odata4analyt" +
            "ics.ParametrizationRequest : any\r\nsap.ui.model.odata.Filter[] : sap.ui.model.Fil" +
            "ter[]\r\nsap.ui.model.odata.OdataListBinding : sap.ui.model.odata.ODataListBinding" +
            "\r\nsap.ui.model.odata.v4.lib._MetadataRequestor : any\r\nsap.ui.suite.TaskCircleCol" +
            "or : any\r\nsap.ui.test.qunit : any\r\nScrollEnablement : sap.ui.core.delegate.Scrol" +
            "lEnablement\r\nsting[] : string[]\r\nString : string\r\nstring[] : string[]\r\nString[] " +
            ": string[]\r\nTablePersoController : any\r\nTablePersoDialog : any\r\nTouch : any\r\nTou" +
            "chList : any\r\ntrue : boolean\r\nundefined : any\r\nWindow : any")]
        public string TypeReplacements {
            get {
                return ((string)(this["TypeReplacements"]));
            }
            set {
                this["TypeReplacements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"sap/m/designtime/api.json
sap/tnt/designtime/api.json
sap/ui/commons/designtime/api.json
sap/ui/core/designtime/api.json
sap/ui/demokit/designtime/api.json
sap/ui/dt/designtime/api.json
sap/ui/layout/designtime/api.json
sap/ui/suite/designtime/api.json
sap/ui/table/designtime/api.json
sap/ui/unified/designtime/api.json
sap/ui/ux3/designtime/api.json
sap/uxap/designtime/api.json")]
        public string RestEndpoints {
            get {
                return ((string)(this["RestEndpoints"]));
            }
            set {
                this["RestEndpoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputFolder {
            get {
                return ((string)(this["OutputFolder"]));
            }
            set {
                this["OutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://openui5.hana.ondemand.com/test-resources")]
        public string ServiceAddress {
            get {
                return ((string)(this["ServiceAddress"]));
            }
            set {
                this["ServiceAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.40")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"jQuery.sap.act : Ui5Enum
jQuery.sap.history.NavType : Ui5Enum
jQuery.sap.interaction : Ui5Enum
jQuery.sap.KeyCodes : Ui5Enum
jQuery.sap.log.Level : Ui5Enum
jQuery.sap.PseudoEvents : Ui5Enum
jQuery.sap.storage.Type : Ui5Enum
sap.m.MessageBox.Action : Ui5Enum
sap.m.MessageBox.Icon : Ui5Enum
sap.ui.core.BusyIndicator : Ui5Enum
sap.ui.core.BusyIndicatorUtils : Ui5Enum
sap.ui.core.Collision : string
sap.ui.core.CSSColor : string
sap.ui.core.CSSSize : string
sap.ui.core.delegate : Ui5Enum
sap.ui.core.Dock : string
sap.ui.core.ID : string
sap.ui.core.message : Ui5Enum
sap.ui.core.mvc : Ui5Enum
sap.ui.core.Popup.Dock : string
sap.ui.core.theming : Ui5Enum
sap.ui.core.URI : string
sap.ui.core.ws.ReadyState : Ui5Enum
sap.ui.layout.BlockBackgroundType : Ui5Enum
sap.ui.layout.form.GridElementCells : string|number
sap.ui.layout.GridIndent : string
sap.ui.layout.GridSpan : string
sap.ui.model.analytics.odata4analytics.SortOrder : Ui5Enum
sap.ui.model.BindingMode : Ui5Enum
sap.ui.model.FilterOperator : Ui5Enum
sap.ui.model.FilterType : Ui5Enum
sap.ui.model.odata.CountMode : Ui5Enum
sap.ui.model.odata.ODataUtils : Ui5Enum
sap.ui.model.TreeBindingUtils : Ui5Enum
sap.ui.SplitterSize : string
sap.ui.suite.TaskCircleColor : string
sap.uxap.BlockBaseColumnLayout : string|number")]
        public string TypeDefinitions {
            get {
                return ((string)(this["TypeDefinitions"]));
            }
            set {
                this["TypeDefinitions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extend :\r\ngetMetadata :")]
        public string SkipMethods {
            get {
                return ((string)(this["SkipMethods"]));
            }
            set {
                this["SkipMethods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"# file: jQuery.d.ts
REPLACE(sap.ui, sapui)
ADD(@start, import sapui = sap.ui;)
# file: sap.m.d.ts
REMOVE(import sapimport = sap;)
# file: sap.tnt.d.ts
REMOVE(import sapimport = sap;)
# file: sap.uxap.d.ts
REMOVE(import sapimport = sap;)
# file: sap.ui.d.ts
REMOVE(import sapimport = sap;)")]
        public string PostProcessing {
            get {
                return ((string)(this["PostProcessing"]));
            }
            set {
                this["PostProcessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuppressVisibility {
            get {
                return ((bool)(this["SuppressVisibility"]));
            }
            set {
                this["SuppressVisibility"] = value;
            }
        }
    }
}
